name: Hello RISC-V

on:
  workflow_dispatch:
  workflow_call:

jobs:
  apt:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-riscv]
    steps:
      - run: sudo apt update && sudo apt install -y vim
