name: Hello RISC-V

on:
  workflow_dispatch:
  workflow_call:

jobs:
  ccache:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-riscv]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          variant: ccache
          key: ccache-${{ matrix.runs-on }}
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Build
        run: |
          set -eux -o pipefail
          which ccache
          ccache --version
          ccache --zero-stats
          cd ccache-demo
          cmake -B build
          cmake --build build --verbose
          ./build/hello
          ccache --show-stats -vv

  sccache:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-24.04
          # - ubuntu-24.04-riscv # https://github.com/mozilla/sccache/issues/2681
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure sccache
        uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: sccache-${{ matrix.runs-on }}
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Build
        run: |
          set -eux -o pipefail
          which sccache
          sccache --version
          cd ccache-demo
          cmake -B build
          cmake --build build --verbose
          ./build/hello
          sccache --show-adv-stats