name: Hello RISC-V

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04-riscv, ubuntu-24.04]
    steps:
      - run: echo "hello from $(uname -m)"

  container: { uses: $/.github/workflows/container.yml }
  apt: { uses: $/.github/workflows/apt.yml }
  ccache: { uses: $/.github/workflows/ccache.yml }
  debug: { uses: $/.github/workflows/debug.yml }
  setup-go: { uses: $/.github/workflows/setup-go.yml }
  setup-java: { uses: $/.github/workflows/setup-java.yml }
  setup-python: { uses: $/.github/workflows/setup-python.yml }

